version: '3'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
  task_manager:
    build: ./
    container_name: task_manager
    image: task_manager
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/task_manager
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    ports:
      - "8080:8080"
